language: rust

matrix:
  include:
    - rust: 1.31.0
    - rust: stable
    - rust: nightly
      env: TRAVIS_NIGHTLY=true

script:
  - if [[ "$TRAVIS_NIGHTLY" == "true" ]]; then cargo test --verbose --all-features; fi
  - if [[ "$TRAVIS_NIGHTLY" == "true" ]]; then cargo bench --verbose --all-features --no-run; fi
  - if [[ "$TRAVIS_NIGHTLY" != "true" ]]; then cargo test --verbose; fi

cache: cargo
